const LEVEL1 = [
	[   null,   null,   null, [1, 0] ],
	[ [1, 0], [1, 0],   null,   null ],
	[   null,   null,   null, [1, 0] ],
	[   null,   null,   null,   null ],
	[ [1, 0],   null, [1, 0], [1, 0] ],
	[   null,   null,   null,   null ],
	[ [1, 0],   null, [1, 0], [1, 0] ],
	[   null,   null,   null,   null ],
	[ [1, 0],   null,   null, [1, 0] ],
	[   null,   null,   null,   null ],
	[ [1, 0],   null,   null, [1, 0] ],
	[   null,   null,   null,   null ],
	[ [0, 0], [2,18],   null, [1, 0] ],
	[   null,   null,   null,   null ],
	[ [0, 0],   null,   null, [1, 0] ],
	[   null,   null, [0,10],   null ],
	[ [1, 0],   null,   null, [1, 0] ],
	[   null,   null, [1, 0],   null,],
	[ [0, 0],   null,   null, [1, 0] ],
	[   null,   null, [1, 0],   null,],
	[   null,   null,   null, [1, 0] ],
	[   null,   null,   null,   null,],
	[   null,   null, [1, 0], [1, 0] ],
	[   null, [1,10],   null,   null,],
	[   null,   null,   null, [1, 0] ],
	[   null, [0, 0],   null,   null,],
	[   null,   null, [1, 0], [1, 0] ],
	[   null,   null,   null,   null ],
	[   null,   null,   null,   null ],
	[   null,   null,   null,   null ],
	[ [0, 0], [1, 0],   null,   null ],
	[   null,   null, [1, 0],   null ],
	[ [1, 0], [1, 0],   null,   null ],
	[   null,   null,   null,   null ],
	[   null,   null,   null,   null ],
	[   null,   null, [1, 0],   null ],
	[   null,   null,   null, [1, 0] ]];
